name: Android CI

on:
  push:
    branches: [ "main", "develop", "coreFunctions-AndUI" ]
  pull_request:
    branches: [ "main", "develop", "coreFunctions-AndUI" ]

jobs:
  build:
    runs-on: ubuntu-latest # Runner-Umgebung

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Standard-Action zum Auschecken

      - name: sentry login
        run: sentry-cli login --auth-token $GITHUB_TOKEN

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Deine JDK-Version für Gradle
          distribution: 'temurin' # Oder eine andere Distribution
          cache: gradle # Abhängigkeiten zwischenspeichern

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # Sicherstellen, dass gradlew ausführbar ist

      - name: Build with Gradle
        run: ./gradlew build # Führt alle Checks, Tests und Builds aus, die im 'build'-Task definiert sind

    # Optional: Lint-Check explizit ausführen (oft schon in 'build' enthalten)
    # - name: Run Lint
    #   run: ./gradlew lintDebug

    # Optional: Unit-Tests explizit ausführen (oft schon in 'build' enthalten)
    # - name: Run unit tests
    #   run: ./gradlew testDebugUnitTest

    # Optional: APK als Artefakt hochladen
    # - name: Upload APK
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: app-debug.apk
    #     path: app/build/outputs/apk/debug/app-debug.apk
