name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest # Runner-Umgebung
    env: # Environment variables for this job
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      # Optional,but often useful for Sentry:
      SENTRY_ORG: privat-jb
      SENTRY_PROJECT: vivid
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Standard-Action zum Auschecken

      - name: Setup Sentry CLI
        uses: matbour/setup-sentry-cli@v1
        with:
          version: latest # optional if 'latest'
   #       url: https://sentry.yourcompany.com # optional if you are using https://sentry.io
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          organization: private-jb
          project: vivid

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Deine JDK-Version für Gradle
          distribution: 'temurin' # Oder eine andere Distribution
          cache: gradle # Abhängigkeiten zwischenspeichern

      - name: Decode and Install Keystore
        # Führt diesen Schritt nur aus, wenn das Secret vorhanden ist
        if: secrets.SIGNING_KEY_STORE_BASE64 != ''
        env:
          # Die Umgebungsvariable für den Dateipfad setzen
          SIGNING_KEY_STORE_FILE: ${{ runner.temp }}/keystore.jks
          # Secrets in Umgebungsvariablen für den nächsten Schritt verfügbar machen
          SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          echo "Decoding keystore from secret..."
          echo $SIGNING_KEY_STORE_BASE64 | base64 --decode > $SIGNING_KEY_STORE_FILE
          echo "Keystore decoded to $SIGNING_KEY_STORE_FILE"
          - name: Build with Gradle
            env:
              # Die Secrets als Umgebungsvariablen für Gradle bereitstellen
              SIGNING_KEY_STORE_FILE: ${{ runner.temp }}/keystore.jks
              SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
              SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
              SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
            run: ./gradlew assembleRelease
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # Sicherstellen, dass gradlew ausführbar ist

      - name: Build with Gradle
        run: ./gradlew build # Führt alle Checks, Tests und Builds aus, die im 'build'-Task definiert sind

    # Optional: Lint-Check explizit ausführen (oft schon in 'build' enthalten)
    # - name: Run Lint
    #   run: ./gradlew lintDebug

    # Optional: Unit-Tests explizit ausführen (oft schon in 'build' enthalten)
    # - name: Run unit tests
    #   run: ./gradlew testDebugUnitTest

    # Optional: APK als Artefakt hochladen
    # - name: Upload APK
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: app-debug.apk
    #     path: app/build/outputs/apk/debug/app-debug.apk
